<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_3</name>
   <tag></tag>
   <elementGuidId>5262cbc8-530a-40d8-9e09-05091c22dac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > button.css-bugrro-unf-pagination-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[6]/nav/ul/li[4]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b78109c6-5f12-4090-8ef1-075f4f3c7329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-bugrro-unf-pagination-item</value>
      <webElementGuid>3153a30d-9fd0-421e-b789-e84384982310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unf</name>
      <type>Main</type>
      <value>pagination-item</value>
      <webElementGuid>d31a2eff-da0b-40fb-9686-fe3fdeb50272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>079a7243-badc-4633-8923-c5f13754b936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Laman 3</value>
      <webElementGuid>e250257e-3650-4730-a228-1729c878f22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c1dca9e-eddb-45ea-8135-6eea78a98238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>05239ccd-c95e-46c8-acb1-f78017f95c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[@class=&quot;css-gvoll6&quot;]/nav[@class=&quot;css-txlndr-unf-pagination&quot;]/ul[@class=&quot;css-1ni9y5x-unf-pagination-items&quot;]/li[4]/button[@class=&quot;css-bugrro-unf-pagination-item&quot;]</value>
      <webElementGuid>2acf6989-eab1-49fe-b56b-67d2acad7fec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[6]/nav/ul/li[4]/button</value>
      <webElementGuid>c46f45d4-8e88-4efc-a98c-c97dd9c7a7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual 14'])[1]/following::button[4]</value>
      <webElementGuid>990efb3e-f77e-46d1-b347-7ce83f8bb081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gudang-HP'])[4]/following::button[4]</value>
      <webElementGuid>0ffdbb5c-5763-4324-8cee-9086c771d352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Tokopedia'])[2]/preceding::button[2]</value>
      <webElementGuid>c4fd016a-7e32-4eea-a1ce-d1ee0252719c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hak Kekayaan Intelektual'])[1]/preceding::button[2]</value>
      <webElementGuid>87ae07f5-6b1e-45ed-8b2e-6414b3e818c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>dd8c4b12-c1db-431c-88f3-277b232e9515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>7b6fbdbe-06ef-4444-b31d-859ea2de03cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '3' or . = '3')]</value>
      <webElementGuid>d716dc13-6002-4a1f-b350-520f79ba729b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
