<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KategoriiPhone 14 Pro di goodponselIpho_b36d6c</name>
   <tag></tag>
   <elementGuidId>6649a3d2-9fb1-4939-bb55-350ea2323647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-12jp264.e90swyx2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09566d5e-8d56-40f4-b168-feb0492f62fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-12jp264 e90swyx2</value>
      <webElementGuid>27f2b3b0-cb53-4c9b-9458-077c6dd018b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KategoriiPhone 14 Pro di goodponselIphone 14 Pro di Promo Hari Iniiphone 14 proiphone 14 pro maxiphone 14 pro iboxiphone 14 pro max iboxiphone 14 pro casePencarian terkaitiphone 13 proiphone 14samsung s23 ultrasamsung s23case iphone 14 promacbook air m2TokoiPhone 14 promax HDCJakartaIphone 14 Pro Max 128Gb Fullset MulusBekasi  Masuk Daftar </value>
      <webElementGuid>096511ea-085e-49f5-abbd-9c857e58a347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-12jp264 e90swyx2&quot;]</value>
      <webElementGuid>d5ce74e4-c311-45e8-b7c1-0e4cd3cbbb45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]</value>
      <webElementGuid>c09a8b39-1e1f-425d-8e6d-25d5ad983378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokopedia Care'])[1]/following::div[1]</value>
      <webElementGuid>7e5bec30-73a4-4d94-9689-c605bb42da64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/following::div[1]</value>
      <webElementGuid>29b61fb0-dff6-4692-8080-0f9158afe66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]</value>
      <webElementGuid>098c885c-ba39-4921-bcfd-b5fb7bb5be5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KategoriiPhone 14 Pro di goodponselIphone 14 Pro di Promo Hari Iniiphone 14 proiphone 14 pro maxiphone 14 pro iboxiphone 14 pro max iboxiphone 14 pro casePencarian terkaitiphone 13 proiphone 14samsung s23 ultrasamsung s23case iphone 14 promacbook air m2TokoiPhone 14 promax HDCJakartaIphone 14 Pro Max 128Gb Fullset MulusBekasi  Masuk Daftar ' or . = 'KategoriiPhone 14 Pro di goodponselIphone 14 Pro di Promo Hari Iniiphone 14 proiphone 14 pro maxiphone 14 pro iboxiphone 14 pro max iboxiphone 14 pro casePencarian terkaitiphone 13 proiphone 14samsung s23 ultrasamsung s23case iphone 14 promacbook air m2TokoiPhone 14 promax HDCJakartaIphone 14 Pro Max 128Gb Fullset MulusBekasi  Masuk Daftar ')]</value>
      <webElementGuid>fa77e63d-0629-49b8-80b9-349f6e751991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
